language: go

git:
  depth: 3
  submodules: false

branches:
  only:
    - master

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x

script:
  - make check

after_sucess:
  - go get -u github.com/haya14busa/goverage
  - goverage -v -coverprofile=coverage.txt -covermode=count ./...
  - bash <(curl -s https://codecov.io/bash)
